# Site settings
title: Bem-vindo!
email: 
description: > # this means to ignore newlines until "baseurl:"
  Linux, software livre, livros, cinema, trabalhos manuais, enfim, tudo aquilo de que eu gosto...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://id9.github.io/"
twitter_username: 
github_username:  

# Build settings
markdown: redcarpet
